name: Publish Package to NPM
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js for Trusted Publish
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm install -g npm@latest

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --if-present

      - name: Publish package
        run: npm publish --access public --tag beta
